site_name: mheatmap
site_url: https://mheatmap.qqgjyx.com/
theme:
  name: material

plugins:
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - "import sys; sys.path.insert(0, './src')"  # Use './src' to point to the correct path
          options:
            docstring_style: numpy
  - offline
  - search
  - tags
  # - awesome-pages
